#include <stm32f103xx.toml>

[clock.source]
value = 'pll'

[clock.pll_source]
value = 'hsi_div2'

[clock.pll_multiplier]
value = 12

[clock.ahb_prescale]
value = 1

[clock.apb1_prescale]
value = 2

[clock.apb2_prescale]
value = 1

[clock.adc_prescale]
value = 2

[clock.usb_prescale]
value = 1.0

[flash.latency]
value = 1
